name: Publish
on:
  push:
    branches:
      - "main"

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install asciidoctor
        run: npm install -g asciidoctor asciidoctor-chunker

      - name: Build
        run: asciidoctor livro.adoc -o index.html

      # - name: Split
      #   run: asciidoctor-chunker index.html -o output

      - name: Publish
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "index.html"
          # source: "output/*"
          target: "~/pythonfluente.com/"
